---
title: "qPCR"
output:
  pdf_document: default
  html_document: default
date: "2023-07-21"
---

```{r}
library(tidyverse)
```

Converted Cq value to aev with: =10^(-(0.3012 * E2) + 11.434)



```{r}
qpcr <- read.csv("../data/SR-qpcr-data-1.csv", header = TRUE) 
```



```{r}
ggplot(data = qpcr, mapping = aes(x = Subgroup, y = CqMean)) + 
  geom_boxplot() +
  facet_wrap('Target')


```


```{r}

ggplot(data = qpcr, mapping = aes(x = Subgroup, y = aev)) + 
  geom_boxplot() +
  facet_wrap('Target') +
  coord_cartesian(ylim = c(1000, 175000))

```


```{r}
qpcr %>%
  filter(Target == "Cg_18s(1408/9)") %>%
ggplot(mapping = aes(x = Subgroup, y = aev)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = history), width = 0.1, alpha = 0.7)


```
```{r}
qpcr %>%
  filter(Target == "Cg_GAPDH(1172/3)")  %>%
ggplot(mapping = aes(x = Subgroup, y = aev)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = history), width = 0.1, alpha = 0.7)

```



```{r}
qpcr %>%
  filter(Target == "Cg_ATPsynthase(1385/6)")  %>%
ggplot(mapping = aes(x = Subgroup, y = aev)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = history), width = 0.1, alpha = 0.7)

```


```{r}
qpcr %>%
  filter(Target == "Cg_citratesynthase(1383/4)")  %>%
ggplot(mapping = aes(x = Subgroup, y = aev)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = history), width = 0.1, alpha = 0.7)

```