---
title: "qpcr normalization"
output: html_document
date: "2023-07-26"
---

```{r}
library(tidyverse)
```





```{r}
nqpcr <- read.csv("../data/qpcr-fold.csv", header = TRUE) 
```



```{r}
ggplot(data = nqpcr, mapping = aes(x = Subgroup, y = fold)) + 
  geom_boxplot()


```

```{r}
nqpcr %>%
  filter(Target == "Cg_ATPsynthase(1385/6)") %>%
ggplot(mapping = aes(x = Subgroup, y = fold)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)


```

```{r}
nqpcr %>%
  filter(Target == "Cg_citratesynthase(1383/4)") %>%
ggplot(mapping = aes(x = Subgroup, y = fold)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)


```


```{r}
nqpcr %>%
  filter(Target == "Cg_GAPDH(1172/3)") %>%
ggplot(mapping = aes(x = Subgroup, y = fold)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)


```

```{r}
nqpcr %>%
  filter(Target == "Cg_GAPDH(1172/3)")  %>%
ggplot(mapping = aes(x = Subgroup, y = fold)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)

```


```{r}
nqpcr %>%
  filter(Target == "IL-17_internal(256/7)")  %>%
ggplot(mapping = aes(x = Subgroup, y = fold)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)

```


```{r}
nqpcr %>%
  filter(Target == "Cg_HSP70(598/9)")  %>%
ggplot(mapping = aes(x = Subgroup, y = fold)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)

```

```{r}
nqpcr %>%
  filter(Target == "Cg_HSP90(1532/3)")  %>%
ggplot(mapping = aes(x = Subgroup, y = fold)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)

```

```{r}
nqpcr %>%
  filter(Target == "Cg_VIPERIN(1828/9)")  %>%
ggplot(mapping = aes(x = Subgroup, y = fold)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)

```

```{r}
nqpcr %>%
  filter(Target == "Cg_Def(1160/1)")  %>%
ggplot(mapping = aes(x = Subgroup, y = fold)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)

```