---
title: "AEV-graphs"
author: "Noah Krebs"
date: "2023-07-25"
output:
  word_document: default
  html_document: default
---
```{r}
library(tidyverse)
```

```{r}
qpcra <- read.csv("../data/qPCR-data-7-24-1-aev.csv", header = TRUE)

qpcrb <- read.csv("../data/qPCR-data-21-aev.csv", header = TRUE)

qpcrc <- read.csv("../data/qPCRdata-21-4-AEV.csv", header = TRUE)
```

```{r}
qpcra %>%
  filter(Target == "Cg_18s(1408/9)") %>%
ggplot(mapping = aes(x = Subgroup, y = AEV)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)
```
```{r}
qpcra %>%
  filter(Target == "Cg_Actin(1170/1)") %>%
ggplot(mapping = aes(x = Subgroup, y = AEV)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)
```
```{r}
qpcra %>%
  filter(Target == "Cg_Def(1160/1)") %>%
ggplot(mapping = aes(x = Subgroup, y = AEV)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)
```
```{r}
qpcra %>%
  filter(Target == "IL-17_internal(256/7)") %>%
ggplot(mapping = aes(x = Subgroup, y = AEV)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)
```
```{r}
qpcrb %>%
  filter(Target == "Cg_HSP70(598/9)") %>%
ggplot(mapping = aes(x = Subgroup, y = AEV)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)
```
```{r}
qpcrb %>%
  filter(Target == "Cg_HSP90(1532/3)") %>%
ggplot(mapping = aes(x = Subgroup, y = AEV)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)
```
```{r}
qpcrb %>%
  filter(Target == "Cg_VIPERIN(1828/9)") %>%
ggplot(mapping = aes(x = Subgroup, y = AEV)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)
```
```{r}
qpcrc %>%
  filter(Target == "Cg_18s(1408/9)") %>%
ggplot(mapping = aes(x = Subgroup, y = AEV)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)
```
```{r}
qpcrc %>%
  filter(Target == "Cg_ATPsynthase(1385/6)") %>%
ggplot(mapping = aes(x = Subgroup, y = AEV)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)
```
```{r}
qpcrc %>%
  filter(Target == "Cg_citratesynthase(1383/4)") %>%
ggplot(mapping = aes(x = Subgroup, y = AEV)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)
```
```{r}
qpcrc %>%
  filter(Target == "Cg_GAPDH(1172/3)") %>%
ggplot(mapping = aes(x = Subgroup, y = AEV)) + 
  geom_boxplot()  +
  geom_jitter(aes(color = History), width = 0.1, alpha = 0.7)
```


```{r}
```

