---
title: "Differential response of oysters: polyploidy and environmental stress"
subtitle: "Mentoring Plan"
format: gfm
editor: visual
---

# Introduction

This 10-week research internship will focus primarily on the study of Pacific oysters, specifically investigating how environmental stress factors and triploidy - the condition of having three sets of chromosomes - affect these bivalve mollusks. The Pacific oyster, a key species in marine ecosystems and global aquaculture, possesses a remarkable ability to adapt to a wide range of environmental conditions. However, the increasing stressors resulting from climate change, such as ocean acidification and temperature fluctuations, pose significant challenges to their survival and reproductive success. Furthermore, many Pacific oysters are deliberately bred to be triploid to enhance growth and survival rates. Throughout the internship, we will rigorously examine these interactions, employing a blend of laboratory experimentation and data analysis to explore these intricate dynamics. This research opportunity will provide a comprehensive understanding of the delicate balance between genetic variation, environmental stress, and survival in Pacific oysters, offering valuable insights for future conservation strategies and sustainable aquaculture practices.

# Objectives

-   Document prior research that offers explanation of physiological difference in triploid and diploid oysters

-   Characterize differential gene expression in triploid oysters compared to diploid oysters in response to environmental stress.

-   Evaluate differences in gene copy number variation between diploid and triploid oysters.

# Work Plan

## Week 1

### Readings

-   Lab Culture \@ <https://robertslab.github.io/resources/>

-   Review week 3-5 \@ <https://sr320.github.io/course-fish274-2022/schedule/>

-   <https://www.biorxiv.org/content/10.1101/2023.03.02.530828v1>

### Tasks

Get familiar with GitHub, Slack, electronic labnotebook, Handbook.

Have experimental system established. Plan environmental stress

### Milestones

Have oyster tanks set up

------------------------------------------------------------------------

## Week 2

### Readings

-   [Opportunities in Functional Genomics: A Primer on Lab and Computational Aspects](https://d.pr/f/ngmWkw)

-   

### Tasks

Write up summary of reading in notebook - be sure to hightlight most interesting aspects and areas that could be better explain. Find a/the paper that cites it.

Maintain oysters

Set-up repo for copy number variation analysis

Confirm supplies in inventory

### Milestones

Run environmental stress experiment 
Start copy number variation analysis.

------------------------------------------------------------------------

## Week 3

### Readings

Find 5 papers discussing physiology of triploid and oysters.

### Tasks

Write summary of two papers in notebook and indicate how they relate to project

Sample oysters

Extract RNA

Order Primers

Have initial CNV analysis done

### Milestones

Have RNA from experiment

------------------------------------------------------------------------

## Week 4

### Readings

-   TBD

### Tasks

Write summary of two papers found in week 3 in notebook and indicate how they relate to project

Make cDNA, run test qPCR

### Milestones

Run qPCR\
Write Methods Section(s)

------------------------------------------------------------------------

## Week 5

### Readings

-   TBD

### Tasks

Run qPCR

Functional annotation of CNV results

Find 5 papers discussing physiology of copy number variation in marine inverebtrates

### Milestones

Have preliminary results figure from

Write Results Section(s)

------------------------------------------------------------------------

## Week 6

### Readings

Read two papers on CNV found in Week 5

Tasks

Write summary of two CNV papers

Create final figure for qPCR

### Milestones

Write Discussion Section(s)

------------------------------------------------------------------------

## Week 7

### Readings

Read two papers on CNV found in Week 5

### Tasks

Write summary of two CNV papers

Identify 3-4 key points related to results of both efforts - start Discusssion.

### Milestones

Write Discussion Section(s)

------------------------------------------------------------------------

## Week 8

### Readings

TBD

### Tasks

Present results to lab group for feedback

Write Introduction

### Milestones

Write Introduction Section(s)\
Draft Poster

------------------------------------------------------------------------

## Week 9

### Readings

TBD

### Tasks

TBD

### Milestones

Practice Presentation

------------------------------------------------------------------------

## Week 10

### Readings

TBD

### Tasks

Ensure all data and products are archived, metadata is accurate.

### Milestones

Presentation

------------------------------------------------------------------------

# Expectations

-   Spend approximately 8 hours of effort a day on project

-   Meet minimally once a week with Mentor

-   Ask Mentor / lab members questions all the time.

-   Attend Weekly Lab meetings

-   Post in lab notebook on daily basis. This is meant as a journal / documentation / plan activities.

-   Review communications in Slack.

# Timeline of Program

-   Friday, June 16th: Submit mentoring Plan to me.\
-   Tuesday, June 20th: First Day of Program
-   Wednesday, June 21st: First LSAMP Professional Development Session
-   Week of July 10th: I will check in with the students
-   Wednesday, August 2nd (estimate): If students need to have the LSAMP program get their posters printed they will need to submit a draft. LSAMP will create a group order through Health Sciences Printing Services
-   Sunday, August 13th: Abstracts will be due
-   Wednesday, August 16th: Undergraduate Research Symposium where students will present their research posters
-   Wednesday, August 16th: End of Program Celebration
